version: '3'
services:
  web:
    image: nginx:alpine
    container_name: web
    ports:
      - 80:80
    depends_on:
      - app
    privileged: true
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html

  app:
    image: php:fpm-alpine
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/share/nginx/html
